config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/calcular/:number1/:number2', to: 'calcular#home', as: 'home_now'

  get '/adicionar/:number1/:number2', to: 'adicionar#adicionar', as: 'add_now'

  get '/dividir/:number1/:number2', to: 'dividir#dividir', as: 'div_now'

  get '/subtrair/:number1/:number2', to: 'subtrair#subtrair', as: 'sub_now'

  get '/multiplicar/:number1/:number2', to: 'multiplicar#multiplicar', as: 'mult_now'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/adicionar_controller.rb
class AdicionarController < ApplicationController
    def adicionar

        @number1 = params[:number1].to_i
        @number2 = params[:number2].to_i
        
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calcular_controller.rb
class CalcularController < ApplicationController
    def home
        @number1 = params[:number1]
        @number2 = params[:number2]
        
    end
end

app/controllers/dividir_controller.rb
class DividirController < ApplicationController
    def dividir
        @number1= params[:number1].to_f
        @number2= params[:number2].to_f
    end
end

app/controllers/multiplicar_controller.rb
class MultiplicarController < ApplicationController
    def multiplicar
        @number1 = params[:number1].to_i
        @number2 = params[:number2].to_i
    end

end

app/controllers/subtrair_controller.rb
class SubtrairController < ApplicationController
    def subtrair
        @number1 = params[:number1].to_i
        @number2 = params[:number2].to_i
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adicionar/adicionar.html.erb
<body style="text-align: center;">

    <div>
            <h1>Adição</h1>
        <h3> Resultado: <%= @number1 + @number2 %></h3>

        <h4> <%= link_to "Home", home_now_path %> </h4>
    </div>

</body>

app/views/calcular/home.html.erb
<body style="text-align: center;">

    <div>

            <h1>Calculadora</h1>
        <h3> Valores inceridos: <%= @number1 %> e <%= @number2 %></h3>
        <h3>Você deseja: <br>
        <%= link_to "Somar", add_now_path(@number1,@number2) %> 
        <br>
        <%= link_to "Dividir", div_now_path(@number1,@number2) %>   <br>
        <%= link_to "Subtrair", sub_now_path(@number1,@number2) %>  <br>
        <%= link_to "Multiplicar", mult_now_path(@number1,@number2) %> </h3>
    </div>  
</body>

app/views/dividir/dividir.html.erb
<body style="text-align: center;">

    <div>
            <h1>Divisão</h1>
        <h3> Resultado: <%= @number1 / @number2 %></h3>

        <h4> <%= link_to "Home", home_now_path %> </h4>
    </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarefa1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/multiplicar/multiplicar.html.erb
<body style="text-align: center;">

    <div>
            <h1>Multiplicar</h1>
        <h3> Resultado : <%= @number1%> * <%= @number2%> = <%= @number1 * @number2 %></h3>
        <br>
        <h4> <%= link_to "Home", home_now_path %> </h4>
    </div>

</body>

app/views/subtrair/subtrair.html.erb
<body style="text-align: center;">

    <div>
            <h1>Subtrair</h1>
        <h3> Resultado: <%= @number1 %> - <%= @number2 %> =  <%=@number1 - @number2%> </h3>

        <h4> <%= link_to "Home", home_now_path %> </h4>
    </div>

</body>